### ISSUE TITLE
UI Testing: Fields are moving when clicking on email and next fields and again clicking back on previous inputs

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-6#27]
Hi @muthulaksmi ,

Fields are moving when clicking on email and next fields and again clicking back on previous inputs

Steps to Reproduce:

1)Enter firstname,lastname and username
2)Now,click to enter in Email field
3)Now,click back to username field or password field

Video attached:
[R2.zip](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/files/13632413/R2.zip)

**Comment by muthulaksmi** [comment]
kindly pull the latest code and retest.

**Comment by priyadhawan06** [comment]
It is working fine.So,closing this defect.
