### ISSUE TITLE
UI Testing: No error message On Clicking Submit button:While entering Invalid Firstname,Lastname,Username and Valid Email and Password

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-6#28]
Hi @muthulaksmi ,

 No error message is coming On Clicking Submit button:While entering Invalid Firstname,Lastname,Username and Valid Email and Password

Steps To Reproduce:
1)Enter special characters and numeric value in first name,last name,Username field
2)Entr valid email and password/confirm password
3)Click on Submit Button.

Screenshot attached:

![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/148531903/9207f694-a74d-4add-bc4e-482d4f24a595)

**Comment by muthulaksmi** [comment]
Cleared this error. Kindly check and close the issue.

**Comment by priyadhawan06** [comment]
Hi @muthulaksmi ,
Error message is now reflecting...but not for invalid Username

Kindly refer image.
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/148531903/75a90621-ac1e-4205-9fb7-316c96739084)

**Comment by muthulaksmi** [comment]
check now

**Comment by priyadhawan06** [comment]
Error message should appear for all invalid fields.But,message is only for firstname.

![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/148531903/b37ad6c3-ac4c-43a6-b46b-457d60095b41)

**Comment by muthulaksmi** [comment]
Pull the latest code and retest

**Comment by priyadhawan06** [comment]
It is working fine.So,closing this defect.

![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/148531903/30a70999-70a6-4c18-bdd1-dd4a05bc12e9)
