### ISSUE TITLE
UI Testing - Error message not displayed for already registered User name

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-6#29]
Objective : Validate User Name is Unique
Steps to reproduce:
1) Go to Certificate Service Sign-up Page.
2)Enter valid inputs for firstname, lastname, password in the respective fields
4) Enter invalid email id 
3)Insert existing user name in user name field and click on submit button

Expected result : 
Error message for username and email.

Actual result:
No error message on screen

**Comment by muthulaksmi** [comment]
It is working. Please check

**Comment by SugiGitH** [comment]
Retested the test case and is working fine
