### ISSUE TITLE
UI Testing - Respective error messages not displayed for Username, Email and Password

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-6#30]
Objective : Validate Password
Steps to reproduce:
1) Go to Certificate Service Sign-up Page.
2)Enter valid inputs for firstname, lastname, password in the respective fields
4) Enter already registered email id and Username
3)Insert wrong Confirm password and click on submit button

Expected result : 
Error message for username, email and password

Actual result:
Error message displayed only for password

**Comment by muthulaksmi** [comment]
Cleared the error. pls check and close the issue

**Comment by muthulaksmi** [comment]
cleared the error. pls check and close the issue.

**Comment by muthulaksmi** [comment]
kindly pull the latest code and retest.

**Comment by SugiGitH** [comment]
Error message displayed for Username , Email and Confirm Password
