### ISSUE TITLE
UI Testing - Error message not displayed for 21 characters Firstname and Lastname

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-6#36]
Objective : Verify Maximum Length of first name and last name
Steps to reproduce:
1) Go to Certificate Service Sign-up Page.
2)Enter invalid inputs for firstname, lastname in the respective fields
4) Enter valid username, email id and password
3)IClick on submit button

Expected result : 
Error message for Firstname and Lastname

Actual result:
No error message on screen

**Comment by muthulaksmi** [comment]
It is working. please check.

**Comment by SugiGitH** [comment]
Retested the test case and can able to see the error message and the corresponding tool tip.
