### ISSUE TITLE
UI Testing - User name NOT accepts 16 characters

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-6#37]
Objective : Verify Maximum Length of Username
Steps to reproduce:
1)Enter valid inputs for firstname,lastname,email,password
2)Enter username with 16 characters

Expected result : 
The user should be navigated to Login page

Actual result:
** Please enter valid UserName. must be min of 8 char and max 16.

Note : This issue present for 15 characters also

**Comment by muthulaksmi** [comment]
It is working. pls check

**Comment by SugiGitH** [comment]
Re-tested and is working fine
