### ISSUE TITLE
UI Testing - Min and max character length validation for Confirm password not working

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-6#39]
Objective : Validate Confirm password
Steps to reproduce:
1) Go to Certificate Service Sign-up Page.
2) Enter valid inputs in the respective fields
3) Enter password with 7 character length -- Note: Error message displayed for this to enter password with 8 to 16 character length
4)Enter confirm password same as password with 7 character length

Expected result : 
Error message for confirm password also 

Actual result:
No error message on screen and it got displayed after clicking submit button

**Comment by muthulaksmi** [comment]
confirm password should match with password field. no other validation required.

**Comment by SugiGitH** [comment]
As per Muthu's suggestion , closing the issue
