### ISSUE TITLE
UI Testing - Appropriate error message not displayed for the inputs with SPACES

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-6#44]
Objective : Check all fields with invalid credentials(with spaces in between)
Steps to reproduce:
1) Go to Certificate Service Sign-up Page.
2)Enter invalid inputs for firstname, lastname, password in the respective fields with spaces
3) Enter invalid email id with spaces
4)Insert invalid user name in user name field with spaces and click on submit button

Expected result : 
Error message for all the fields should be displayed "to NOT enter spaces"

**Comment by muthulaksmi** [comment]
Kindly pull the latest code and retest.

**Comment by SugiGitH** [comment]
Re- tested and working fine
