### ISSUE TITLE
proper message is not displaying 

### ISSUE THREAD

**Issue by reshuripple** [Ripples2023/Ripples2023Repo-Sprint-6#45]
For sign in page message is coming login failed which should be changed to sign in failed
[Uploading Error.docx…]()

**Comment by muthulaksmi** [comment]
the file is not opening for me

**Comment by reshuripple** [comment]
yes muthu its not opening ... actually when you are not able to sign in that time login failed message is displaying which should be changed to Sign in failed. As we have changed the page name from login to sign in.

**Comment by reshuripple** [comment]
working fine
