### ISSUE TITLE
Sign up is successful with invalid email id

### ISSUE THREAD

**Issue by reshuripple** [Ripples2023/Ripples2023Repo-Sprint-6#47]
Sign up is successful with invalid email id

**Comment by reshuripple** [comment]
[Email Invalid.docx](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/files/13635919/Email.Invalid.docx)
attaching the image

**Comment by swathigbangera** [comment]
@reshuripple  Required changes are done. Kindly test and let us know.
![47](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/42664214/9b353644-a5ac-4761-b392-fe14f1a79c06)

**Comment by reshuripple** [comment]
tested and its not taking any invalid email id
