### ISSUE TITLE
if you keep clicking on tab then alignment of text field is changing

### ISSUE THREAD

**Issue by reshuripple** [Ripples2023/Ripples2023Repo-Sprint-6#48]
attaching the screen shot
[Alignment.docx](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/files/13636555/Alignment.docx)

**Comment by muthulaksmi** [comment]
Kindly pull the latest code and retest.

**Comment by reshuripple** [comment]
working fine closing thebug
