### ISSUE TITLE
all domain are accepted in email field

### ISSUE THREAD

**Issue by reshuripple** [Ripples2023/Ripples2023Repo-Sprint-6#49]
attached is screen shot
[Domain.docx](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/files/13637095/Domain.docx)

**Comment by reshuripple** [comment]
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/148545119/c06656d2-9f4d-4c4a-9c8d-b6d618212f94)

**Comment by swathigbangera** [comment]
@reshuripple valid domain name such as gmail, yahoo, hotmail we can enter. Kindly test and let us know

**Comment by reshuripple** [comment]
Hi Swati tested and its not taking any invalid email id ,but as per design document it should accept only gmail.com. So let me recheck with Arti then i will close the bug.Thanks

**Comment by reshuripple** [comment]
working fine closing the bug
