### ISSUE TITLE
UI Testing:Font type and color is not same for Sign Up and Sign In Page

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-6#51]
Font type and color is not same for Sign Up and Sign In Page

Steps:
1)Go to Sign In page---check the color and font type
2)Click on Sign Up page and check its font color and type

Screenshot attached:
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/148531903/8839734f-2600-4559-aa23-5bb28e1f390a)
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/148531903/08a17814-d1fb-4861-aca0-da5531e54bb2)

**Comment by muthulaksmi** [comment]
Kindly pull the latest code and retest.

**Comment by priyadhawan06** [comment]
Hi Muthu,

Font typeis Italian in Sign In page but not in Sign Up page.Plz make it similar 
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/148531903/2b360c43-de63-4f29-9f7e-4b282c785f77)

**Comment by priyadhawan06** [comment]
It is reflecting same in both pages.So,closing this bug.
