### ISSUE TITLE
UI testing:  Confirm password error to be shown

### ISSUE THREAD

**Issue by nisha552** [Ripples2023/Ripples2023Repo-Sprint-6#53]
Bug description: when enter password and move to confirm password and keep it blank and just click on outside of confirm password , it shown "password is required".... so As per me "Confirm password is required " message should be there.
![confirm password](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/102511041/d5773f3d-8e26-4304-bd8a-c95840fd7e7d)

**Comment by muthulaksmi** [comment]
kindly pull the latest code and retest.

**Comment by nisha552** [comment]
Ok thanks

**Comment by nisha552** [comment]
Retest
Resolved
