### ISSUE TITLE
color mismatch on text field name

### ISSUE THREAD

**Issue by reshuripple** [Ripples2023/Ripples2023Repo-Sprint-6#55]
attaching pic for reference
[Color.docx](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/files/13643884/Color.docx)

**Comment by swathigbangera** [comment]
@reshuripple @muthulaksmi Required changes are done. Kindly test and let us know
![55](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/42664214/e34b3dca-238d-4190-8fd1-223628677d24)

**Comment by reshuripple** [comment]
still mismatch in color is there.

**Comment by muthulaksmi** [comment]
Kindly pull the latest code and check. 
![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/66822334/76959bd7-4401-4536-8bf0-a09d7acf95ea)

**Comment by reshuripple** [comment]
working fine now
