### ISSUE TITLE
UI Testing - Able to register even if the CONFIRM password is wrong

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-6#60]
Objective : Validate Confirm Password
Steps to reproduce:

Go to Certificate Service Sign-up Page.
2)Enter valid inputs for firstname, lastname, username and emailid, password in the respective fields
3)Insert wrong Confirm password and click on submit button

Expected result :
Error message for confirm password

Actual result:
Error message displayed for confirm password but able to register the user

**Comment by reshuripple** [comment]
not a bug

**Comment by SugiGitH** [comment]
By mistake, the issue was closed and hence re-opening again.

**Comment by SugiGitH** [comment]
Retested the bug and is working as expected.
