### ISSUE TITLE
UI Testing: Confirm Password error message is not getting vanished even if same/correct password is given again in password field

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-6#62]
Confirm Password error message is not vanished if same password is given again in password field

Steps to Reproduce:

1)Go to sign Up page
2)Enter valid details
3)Enter password of 7 characters and confirm password of 8 characters
4)Now,go back to password field and enter 8th character
5)Click on submit button---error message in confirm password is still appering and user is able to register

Attaching video:
[Rec.zip](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/files/13691667/Rec.zip)

**Comment by muthulaksmi** [comment]
the error resolved. pls pull the latest code and retest.

**Comment by priyadhawan06** [comment]
Retested this issue and it has been fixed.So,closing this issue.
