### ISSUE TITLE
UI testing: Displayed Error message for Ymail(Y capital)entry in email but not for ymail(y small)

### ISSUE THREAD

**Issue by nisha552** [Ripples2023/Ripples2023Repo-Sprint-6#63]
when entered Ymail.com in email address it shows "enter valid input" error and submit button in inactive state
When  only made changes from Ymail to ymail  in email.  it not display any error message and submit buttons becomes active but after click on submit not registered

![Ymail](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/102511041/999f277e-3185-47f8-a43a-3a07ada4f098)
![ymail1](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/102511041/d29413be-5cc2-4466-a823-e92aebaf2b7d)

**Comment by muthulaksmi** [comment]
The ymail is not added in the backend. that's why you are getting this error. pull merry latest code and check.

**Comment by nisha552** [comment]
Check for Issue 
Retest 
Resolved and  accepted ymail and able to register with the same Gmail
