### ISSUE TITLE
Without selecting any certificate ,while clicking on associate button its showing successfull message

### ISSUE THREAD

**Issue by reshuripple** [Ripples2023/Ripples2023Repo-Sprint-6#67]
attach file for reference
[Association.docx](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/files/13713392/Association.docx)

**Comment by muthulaksmi** [comment]
Pls pull the latest code and retest.

**Comment by reshuripple** [comment]
Hi Muthu yes that error is gone but still success in message box is displaying .

attaching the image
![Uploading Message.PNG…]()

**Comment by swathigbangera** [comment]
Pls pull the latest code and retest.

**Comment by reshuripple** [comment]
tested and closing
