### ISSUE TITLE
UI Testing: Without selecting certificate when click on dissassociate button, Dissassociation Successfull popup shown

### ISSUE THREAD

**Issue by nisha552** [Ripples2023/Ripples2023Repo-Sprint-6#68]
After association certificate
Steps: Click on My Certificate
Click on Dissassociate button

![diassociate](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/102511041/2f12ce7d-19de-4e50-b28f-cc933c21609f)

**Comment by muthulaksmi** [comment]
Pls pull latest code and retest

**Comment by nisha552** [comment]
In error message still "Success" is present....

**Comment by swathigbangera** [comment]
Pls pull the latest code and retest.

**Comment by nisha552** [comment]
Resolved
Retest
Show proper error message
