### ISSUE TITLE
Alignment changes if the Certificate name is long

### ISSUE THREAD

**Issue by SugiGitH** [Ripples2023/Ripples2023Repo-Sprint-6#69]
The S.No alignment has got shifted to left side when the certificate name is long. Please refer the screenshot
[Error.docx](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/files/13714662/Error.docx)

**Comment by swathigbangera** [comment]
Pull the latest code and retest

**Comment by SugiGitH** [comment]
Retested the changes in the latest code and is working as expected.
