### ISSUE TITLE
UI Testing: Two security questions are same in "Select Security Question" Dropdown

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-6#76]
Hi @muthulaksmi ,

In sign Up page,Two security questions are same in "Select Security Question" Dropdown
What is your favorite food?
This question is repeating.

Attaching screenshot:

![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/148531903/1fcf7465-703c-451b-aaaf-4fe8fdd80dd5)

Thanks,
Priya

**Comment by muthulaksmi** [comment]
pls pull the latest code retest.

**Comment by priyadhawan06** [comment]
It is now working fine.So,closing this defect.
