### ISSUE TITLE
UI Testing:Forgot Password link is not clickable

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-6#77]
Hi @muthulaksmi ,

In Sign In Page,Forgot Password link is not clickable at some points.

[RR.zip](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/files/13842139/RR.zip)

Please look into it.

Thanks,
Priya

**Comment by muthulaksmi** [comment]
pls pull the latest code and retest.

**Comment by priyadhawan06** [comment]
This is working fine.So,closing this issue.
