### ISSUE TITLE
UI Testing: When clicking on Password(in forgot password link),it is navigating to Sign Up Page

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-6#78]
Hi @muthulaksmi 

 When clicking on Password(in forgot password link),it is navigating to Sign Up Page and when clicking on Forgot,it is navigating to correct page.

Please refer my below video:

[Pswd.zip](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/files/13842235/Pswd.zip)

Thanks,
Priya

**Comment by muthulaksmi** [comment]
pls pull the latest code and retest

**Comment by priyadhawan06** [comment]
It is now working fine.So,closing this defect.
