### ISSUE TITLE
UI Testing: On entering Single character in Answers in Sign Up page,Registeration got successful

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-6#79]
Hi @muthulaksmi ,

On entering Single character in Answers in Sign Up page,Registeration got successful.

Please refer screenshot

![image](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/148531903/8d84b1ed-3f18-4ff9-8e20-1c7b14a6c9bd)

Thanks,
Priya

**Comment by muthulaksmi** [comment]
pls pull the latest code and retest.

**Comment by priyadhawan06** [comment]
Hi,It is now working fine.So,closing this bug.
