### ISSUE TITLE
UI Testing: On Refreshing forgot password page,Security question is appearing.

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-6#80]
Hi @muthulaksmi ,

On Refreshing forgot password page,Security question is appearing.

Please check video:

[Reset.zip](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/files/13842402/Reset.zip)

Thanks,
Priya

**Comment by muthulaksmi** [comment]
pls pull the latest code and retest.

**Comment by priyadhawan06** [comment]
It is now working fine.So,closing this defect.
