### ISSUE TITLE
UI Testing: In sign Up page,User is getting registered by giving blank spaces in answer

### ISSUE THREAD

**Issue by priyadhawan06** [Ripples2023/Ripples2023Repo-Sprint-6#81]
Hi @muthulaksmi ,

In sign Up page,User is getting registered by giving blank spaces in answer

Steps:
Goto sign Up Page
Fill all inputs with valid details
Now,select any security question
In Answer,click on space bar i.e. enter blank spaces
Submit button gets enabled and user is getting registered.

**Comment by muthulaksmi** [comment]
pls pull the latest code and retest

**Comment by priyadhawan06** [comment]
It is now,working as expected.So,closing this defect.
