### ISSUE TITLE
UI testing SignUp: Security question answer should be Unmasked

### ISSUE THREAD

**Issue by nisha552** [Ripples2023/Ripples2023Repo-Sprint-6#83]
![error1](https://github.com/Ripples2023/Ripples2023Repo-Sprint-6/assets/102511041/05218c04-fdf8-4c19-ac1f-30babad5da8c)

**Comment by muthulaksmi** [comment]
pls pull the latest code and retest

**Comment by nisha552** [comment]
Retest
Resolve
